// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlotGame.Api.Data;

#nullable disable

namespace SlotGame.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317035342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("SlotGame.Api.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.ReelStrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ColumnIndex")
                        .IsUnique();

                    b.ToTable("ReelStrips");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.ReelSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReelStripId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReelStripId", "Position")
                        .IsUnique();

                    b.ToTable("ReelSymbols");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.Spin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FinalMatrixJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalWin")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Spins");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.ReelStrip", b =>
                {
                    b.HasOne("SlotGame.Api.Entities.Game", "Game")
                        .WithMany("ReelStrips")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.ReelSymbol", b =>
                {
                    b.HasOne("SlotGame.Api.Entities.ReelStrip", "ReelStrip")
                        .WithMany("Symbols")
                        .HasForeignKey("ReelStripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReelStrip");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.Spin", b =>
                {
                    b.HasOne("SlotGame.Api.Entities.Game", "Game")
                        .WithMany("Spins")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.Game", b =>
                {
                    b.Navigation("ReelStrips");

                    b.Navigation("Spins");
                });

            modelBuilder.Entity("SlotGame.Api.Entities.ReelStrip", b =>
                {
                    b.Navigation("Symbols");
                });
#pragma warning restore 612, 618
        }
    }
}
